### ISSUE TITLE
App crashes when opening the details view a second time

### ISSUE THREAD

**Issue by fitzsia2** [fitzsia2/PopularMovies#2]
To Reproduce:
1. Start the app.
2. Click a movie.
3. Press the back button.
4. Click another movie (can be same movie)

E/SQLiteLog: (1032) statement aborts at 30: [UPDATE movies SET length=? WHERE movie_db_id = ?] 
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
                  Process: com.afitzwa.android.popularmovies.app, PID: 2463
                  java.lang.RuntimeException: An error occured while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:304)
                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
                      at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
                      at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
                      at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
                      at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
                      at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1576)
                      at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1522)
                      at com.afitzwa.android.popularmovies.app.data.MovieProvider.update(MovieProvider.java:360)
                      at android.content.ContentProvider$Transport.update(ContentProvider.java:328)
                      at android.content.ContentResolver.update(ContentResolver.java:1333)
                      at com.afitzwa.android.popularmovies.app.FetchMovieDetailsTask.doInBackground(FetchMovieDetailsTask.java:113)
                      at com.afitzwa.android.popularmovies.app.FetchMovieDetailsTask.doInBackground(FetchMovieDetailsTask.java:42)
                      at android.os.AsyncTask$2.call(AsyncTask.java:292)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                      at java.lang.Thread.run(Thread.java:818)

**Comment by fitzsia2** [comment]
It looks like this was a concurrency issue.

I stopped saving all movies to the database. Only movies marked as favorites are saved to the database. This reduced the number of transactions with the database as narrowed the context of database calls to the UI thread.
